module.exports = [
  {
    auth_id: 'AaZjGoX4K',
    auth_name: '文章管理',
    auth_description: '文章管理',
    auth_father_id: '',
    auth_father_name: '',
    auth_url: 'article_mange',
    auth_sort: 1,
    auth_type: '1',
    enable: true
  },
  {
    auth_description: 'dasddasd',
    auth_id: 'M5_VrV7vx',
    auth_name: '文章汇总',
    auth_father_id: 'AaZjGoX4K',
    auth_father_name: '文章管理',
    auth_sort: 0,
    auth_type: '1',
    auth_url: 'article',
    enable: true
  },
  {
    auth_description: '查看文章列表的权限',
    auth_id: 'Jh8z1f7yt',
    auth_name: '获取文章列表',
    auth_father_id: 'M5_VrV7vx',
    auth_father_name: '文章汇总',
    auth_sort: 5,
    auth_type: '2',
    auth_url: '/article/list',
    enable: false
  },
  {
    auth_description: '修改文章的一些字段',
    auth_id: 'nGyHv8SMz',
    auth_name: '更新文章',
    auth_father_id: 'M5_VrV7vx',
    auth_father_name: '文章汇总',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/article/edit',
    enable: false
  },
  {
    auth_description: '删除文章的权限',
    auth_id: 'HtqdfZid0',
    auth_name: '删除文章',
    auth_father_id: 'M5_VrV7vx',
    auth_father_name: '文章汇总',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/article/delete',
    enable: false
  },
  {
    auth_description: '文章的标签栏修改',
    auth_id: 'QZuaQAqRs',
    auth_name: '文章标签',
    auth_father_id: 'AaZjGoX4K',
    auth_father_name: '文章管理',
    auth_sort: 1,
    auth_type: '1',
    auth_url: 'article_tag',
    enable: true
  },
  {
    auth_description: '获取文章所有的标签列表，并且分页',
    auth_id: 'fkXCvFOth',
    auth_name: '获取文章标签列表',
    auth_father_id: 'QZuaQAqRs',
    auth_father_name: '文章标签',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/article-tag/list',
    enable: false
  },
  {
    auth_description: '创建文章标签',
    auth_id: 'zJfUPY51P',
    auth_name: '创建文章标签',
    auth_father_id: 'QZuaQAqRs',
    auth_father_name: '文章标签',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/article-tag/create',
    enable: false
  },
  {
    auth_description: '更新文章标签',
    auth_id: 'r-tDtqr94',
    auth_name: '更新文章标签',
    auth_father_id: 'QZuaQAqRs',
    auth_father_name: '文章标签',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/article-tag/update',
    enable: false
  },
  {
    auth_description: '删除文章标签',
    auth_id: 'HkgJdDzEm',
    auth_name: '删除文章标签',
    auth_father_id: 'QZuaQAqRs',
    auth_father_name: '文章标签',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/article-tag/delete',
    enable: false
  },
  {
    auth_description: '文章专栏',
    auth_id: 'wFaa7X0k-',
    auth_name: '文章专栏',
    auth_father_id: 'AaZjGoX4K',
    auth_father_name: '文章管理',
    auth_sort: 2,
    auth_type: '1',
    auth_url: 'article_column',
    enable: true
  },
  {
    auth_description: '获取文章专栏列表',
    auth_id: 'vljPAaWsL',
    auth_name: '获取文章专栏列表',
    auth_father_id: 'wFaa7X0k-',
    auth_father_name: '文章专栏',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/article-column/list',
    enable: false
  },
  {
    auth_description: '创建文章专栏',
    auth_id: 'wamK-ehtL',
    auth_name: '创建文章专栏',
    auth_father_id: 'wFaa7X0k-',
    auth_father_name: '文章专栏',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/article-column/create',
    enable: false
  },
  {
    auth_description: '更新文章专栏',
    auth_id: 'C3WtKzxS_',
    auth_name: '更新文章专栏',
    auth_father_id: 'wFaa7X0k-',
    auth_father_name: '文章专栏',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/article-column/update',
    enable: false
  },
  {
    auth_description: '删除文章专栏',
    auth_id: 'klUA63clP',
    auth_name: '删除文章专栏',
    auth_father_id: 'wFaa7X0k-',
    auth_father_name: '文章专栏',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/article-column/delete',
    enable: false
  },
  {
    auth_description: '用户管理',
    auth_id: 'f-_KRK5ZL',
    auth_name: '用户管理',
    auth_father_id: '',
    auth_father_name: '',
    auth_sort: 1,
    auth_type: '1',
    auth_url: 'user_manger',
    enable: true
  },
  {
    auth_description: '用户管理',
    auth_id: 'lnRP0Lc5L',
    auth_name: '用户',
    auth_father_id: 'f-_KRK5ZL',
    auth_father_name: '用户管理',
    auth_sort: 0,
    auth_type: '1',
    auth_url: 'user',
    enable: true
  },
  {
    auth_description: '获取用户列表',
    auth_id: 'YaLP9BQoz',
    auth_name: '获取用户列表',
    auth_father_id: 'lnRP0Lc5L',
    auth_father_name: '用户',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/user/list',
    enable: false
  },
  {
    auth_description: '更新用户',
    auth_id: 'm9a-NQsky',
    auth_name: '更新用户',
    auth_father_id: 'lnRP0Lc5L',
    auth_father_name: '用户',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/user/edit',
    enable: false
  },
  {
    auth_description: '删除用户',
    auth_id: 'PUDwKVudl',
    auth_name: '删除用户',
    auth_father_id: 'lnRP0Lc5L',
    auth_father_name: '用户',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/user/delete',
    enable: false
  },
  {
    auth_description: '用户角色',
    auth_id: 'Fg5quebwd',
    auth_name: '用户角色',
    auth_father_id: 'f-_KRK5ZL',
    auth_father_name: '用户管理',
    auth_sort: 1,
    auth_type: '1',
    auth_url: 'user_role',
    enable: true
  },
  {
    auth_description: '获取用户角色列表',
    auth_id: 'orz0bQnAV',
    auth_name: '获取用户角色列表',
    auth_father_id: 'Fg5quebwd',
    auth_father_name: '用户角色',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/user-role/list',
    enable: false
  },
  {
    auth_description: '创建用户角色',
    auth_id: 'FWJS6cW_t',
    auth_name: '创建用户角色',
    auth_father_id: 'Fg5quebwd',
    auth_father_name: '用户角色',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/user-role/create',
    enable: false
  },
  {
    auth_description: '获取全部用户角色',
    auth_id: 'XFLI-Xiu9',
    auth_name: '获取全部用户角色',
    auth_father_id: 'Fg5quebwd',
    auth_father_name: '用户角色',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/user-role/all',
    enable: false
  },
  {
    auth_description: '更新用户角色',
    auth_id: 'rc8PyN-7e',
    auth_name: '更新用户角色',
    auth_father_id: 'Fg5quebwd',
    auth_father_name: '用户角色',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/user-role/update',
    enable: false
  },
  {
    auth_description: '删除用户角色',
    auth_id: 'FLcVmwUGf',
    auth_name: '删除用户角色',
    auth_father_id: 'Fg5quebwd',
    auth_father_name: '用户角色',
    auth_sort: 4,
    auth_type: '2',
    auth_url: '/user-role/delete',
    enable: false
  },
  {
    auth_description: '评论管理',
    auth_id: 'yoUnDy1tf',
    auth_name: '评论管理',
    auth_father_id: 'f-_KRK5ZL',
    auth_father_name: '用户管理',
    auth_sort: 2,
    auth_type: '1',
    auth_url: 'comment',
    enable: true
  },
  {
    auth_description: '获取评论列表',
    auth_id: 'vAlRwG42i',
    auth_name: '获取评论列表',
    auth_father_id: 'yoUnDy1tf',
    auth_father_name: '评论管理',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/comment/list',
    enable: false
  },
  {
    auth_description: '更新评论',
    auth_id: 'Aj46PocjE',
    auth_name: '更新评论',
    auth_father_id: 'yoUnDy1tf',
    auth_father_name: '评论管理',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/comment/update',
    enable: false
  },
  {
    auth_description: '删除评论',
    auth_id: 'NgMPyBTyt',
    auth_name: '删除评论',
    auth_father_id: 'yoUnDy1tf',
    auth_father_name: '评论管理',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/comment/delete',
    enable: false
  },
  {
    auth_description: '网站管理',
    auth_id: '62EbYFQ4K',
    auth_name: '网站管理',
    auth_father_id: '',
    auth_father_name: '',
    auth_sort: 2,
    auth_type: '1',
    auth_url: 'web',
    enable: true
  },
  {
    auth_description: '图库',
    auth_id: 'Fg332SacC',
    auth_name: '图库',
    auth_father_id: '62EbYFQ4K',
    auth_father_name: '网站管理',
    auth_sort: 1,
    auth_type: '1',
    auth_url: 'picture',
    enable: true
  },
  {
    auth_description: '获取图片列表',
    auth_id: 'hKNBbz3Id',
    auth_name: '获取图片列表',
    auth_father_id: 'Fg332SacC',
    auth_father_name: '图库',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/picture/list',
    enable: false
  },
  {
    auth_description: '上传图片',
    auth_id: '7H5NYaABj',
    auth_name: '上传图片',
    auth_father_id: 'Fg332SacC',
    auth_father_name: '图库',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/picture/create',
    enable: false
  },
  {
    auth_description: '更新图片',
    auth_id: '2tQfFmmDr',
    auth_name: '更新图片',
    auth_father_id: 'Fg332SacC',
    auth_father_name: '图库',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/picture/update',
    enable: false
  },
  {
    auth_description: '删除图片',
    auth_id: 'huW07hjGn',
    auth_name: '删除图片',
    auth_father_id: 'Fg332SacC',
    auth_father_name: '图库',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/picture/delete',
    enable: false
  },
  {
    auth_description: '系统管理',
    auth_id: 'mmnVfpVml',
    auth_name: '系统管理',
    auth_father_id: '',
    auth_father_name: '',
    auth_sort: 3,
    auth_type: '1',
    auth_url: 'admin',
    enable: true
  },
  {
    auth_description: '管理员管理',
    auth_id: 'jKF3lIYO0',
    auth_name: '管理员管理',
    auth_father_id: 'mmnVfpVml',
    auth_father_name: '系统管理',
    auth_sort: 0,
    auth_type: '1',
    auth_url: 'admin_user',
    enable: true
  },
  {
    auth_description: '获取管理员列表',
    auth_id: '51F3xJ4YB',
    auth_name: '获取管理员列表',
    auth_father_id: 'jKF3lIYO0',
    auth_father_name: '管理员管理',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/admin-user/list',
    enable: false
  },
  {
    auth_description: '创建管理员',
    auth_id: 'WCfpKOn6q',
    auth_name: '创建管理员',
    auth_father_id: 'jKF3lIYO0',
    auth_father_name: '管理员管理',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/admin-user/create',
    enable: false
  },
  {
    auth_description: '更新管理员',
    auth_id: '37xmomJUP',
    auth_name: '更新管理员',
    auth_father_id: 'jKF3lIYO0',
    auth_father_name: '管理员管理',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/admin-user/edit',
    enable: false
  },
  {
    auth_description: '删除管理员',
    auth_id: 'rK9yps5-n',
    auth_name: '删除管理员',
    auth_father_id: 'jKF3lIYO0',
    auth_father_name: '管理员管理',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/admin-user/delete',
    enable: false
  },
  {
    auth_description: '角色管理',
    auth_id: 'f__A7Zf22',
    auth_name: '角色管理',
    auth_father_id: 'mmnVfpVml',
    auth_father_name: '系统管理',
    auth_sort: 1,
    auth_type: '1',
    auth_url: 'admin_role',
    enable: true
  },
  {
    auth_description: '获取角色列表',
    auth_id: 'IIjFU1b32',
    auth_name: '获取角色列表',
    auth_father_id: 'f__A7Zf22',
    auth_father_name: '角色管理',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/admin-role/list',
    enable: false
  },
  {
    auth_description: '创建角色',
    auth_id: 'e1AenAQGh',
    auth_name: '创建角色',
    auth_father_id: 'f__A7Zf22',
    auth_father_name: '角色管理',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/admin-role/create',
    enable: false
  },
  {
    auth_description: '更新角色',
    auth_id: 'KE5weIvJm',
    auth_name: '更新角色',
    auth_father_id: 'f__A7Zf22',
    auth_father_name: '角色管理',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/admin-role/edit',
    enable: false
  },
  {
    auth_description: '删除角色',
    auth_id: 'nImMMukuO',
    auth_name: '删除角色',
    auth_father_id: 'f__A7Zf22',
    auth_father_name: '角色管理',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/admin-role/delete',
    enable: false
  },
  {
    auth_description: '权限菜单',
    auth_id: 'kl66VGwzs',
    auth_name: '权限菜单',
    auth_father_id: 'mmnVfpVml',
    auth_father_name: '系统管理',
    auth_sort: 2,
    auth_type: '1',
    auth_url: 'admin_auth',
    enable: true
  },
  {
    auth_description: '获取所有权限菜单',
    auth_id: 'm60NSV9Uf',
    auth_name: '获取所有权限菜单',
    auth_father_id: 'kl66VGwzs',
    auth_father_name: '权限菜单',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/admin-auth/list',
    enable: false
  },
  {
    auth_description: '创建权限',
    auth_id: 'uNcakD-iu',
    auth_name: '创建权限',
    auth_father_id: 'kl66VGwzs',
    auth_father_name: '权限菜单',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/admin-auth/create',
    enable: false
  },
  {
    auth_description: '更新权限',
    auth_id: 'PrlXMUprO',
    auth_name: '更新权限',
    auth_father_id: 'kl66VGwzs',
    auth_father_name: '权限菜单',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/admin-auth/update',
    enable: false
  },
  {
    auth_description: '删除权限',
    auth_id: 'DD7uvMFqf',
    auth_name: '删除权限',
    auth_father_id: 'kl66VGwzs',
    auth_father_name: '权限菜单',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/admin-auth/delete',
    enable: false
  },
  {
    auth_description: '系统配置',
    auth_id: 'EdU0eCL53',
    auth_name: '系统配置',
    auth_father_id: 'mmnVfpVml',
    auth_father_name: '系统管理',
    auth_sort: 3,
    auth_type: '1',
    auth_url: 'system_config',
    enable: false
  },
  {
    auth_description: '查看系统配置',
    auth_id: 'tpm47b-0g',
    auth_name: '查看系统配置',
    auth_father_id: 'EdU0eCL53',
    auth_father_name: '系统配置',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/system-config/info',
    enable: false
  },
  {
    auth_description: '更新系统配置',
    auth_id: 'U2Q9FyWqT',
    auth_name: '更新系统配置',
    auth_father_id: 'EdU0eCL53',
    auth_father_name: '系统配置',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/system-config/update',
    enable: false
  },
  {
    auth_description: '系统日志',
    auth_id: 'F1-0EJhfj',
    auth_name: '系统日志',
    auth_father_id: 'mmnVfpVml',
    auth_father_name: '系统管理',
    auth_sort: 4,
    auth_type: '1',
    auth_url: 'admin_system_log',
    enable: true
  },
  {
    auth_description: '获取系统日志列表',
    auth_id: 'LV2W44Iea',
    auth_name: '获取系统日志列表',
    auth_father_id: 'F1-0EJhfj',
    auth_father_name: '系统日志',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/admin-system-log/list',
    enable: false
  },
  {
    auth_description: '删除系统日志',
    auth_id: 'SpJ9AeDIP',
    auth_name: '删除系统日志',
    auth_father_id: 'F1-0EJhfj',
    auth_father_name: '系统日志',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/admin-system-log/delete',
    enable: false
  },
  {
    auth_description: '一次获取所有的文章标签',
    auth_id: 'sL8GD5TNz',
    auth_name: '获取全部文章标签',
    auth_father_id: 'QZuaQAqRs',
    auth_father_name: '文章标签',
    auth_sort: 4,
    auth_type: '2',
    auth_url: '/article-tag/all',
    enable: false
  },
  {
    auth_description: '一次性获取全部的管理员用户角色',
    auth_id: 'yG6HFsIaE',
    auth_name: '获取全部角色',
    auth_father_id: 'f__A7Zf22',
    auth_father_name: '角色管理',
    auth_sort: 4,
    auth_type: '2',
    auth_url: '/admin-role/all',
    enable: false
  },
  {
    auth_description: '网站配置公告等等',
    auth_id: 'BvTHaZGiy',
    auth_name: '网站配置',
    auth_father_id: '62EbYFQ4K',
    auth_father_name: '网站管理',
    auth_sort: 1,
    auth_type: '1',
    auth_url: 'website_config',
    enable: true
  },
  {
    auth_description: '创建网站配置',
    auth_id: 'JFqDhmDlD',
    auth_name: '创建网站配置',
    auth_father_id: 'BvTHaZGiy',
    auth_father_name: '网站配置',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/options/create',
    enable: false
  },
  {
    auth_description: '更新网站配置',
    auth_id: 'glXE-ZYMj',
    auth_name: '更新网站配置',
    auth_father_id: 'BvTHaZGiy',
    auth_father_name: '网站配置',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/options/update',
    enable: false
  },
  {
    auth_description: '删除网站配置',
    auth_id: 'zrjH_hLgq',
    auth_name: '删除网站配置',
    auth_father_id: 'BvTHaZGiy',
    auth_father_name: '网站配置',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/options/delete',
    enable: false
  },
  {
    auth_description: '获取网站配置项列表',
    auth_id: 'n47GLlyLh',
    auth_name: '获取网站配置项列表',
    auth_father_id: 'BvTHaZGiy',
    auth_father_name: '网站配置',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/options/list',
    enable: false
  },
  {
    auth_description: '用户权限',
    auth_id: '8nzhEmgmS',
    auth_name: '用户权限',
    auth_father_id: 'f-_KRK5ZL',
    auth_father_name: '用户管理',
    auth_sort: 3,
    auth_type: '1',
    auth_url: 'user_auth',
    enable: true
  },
  {
    auth_description: '获取用户权限列表',
    auth_id: 'hDzP4R-nh',
    auth_name: '获取用户权限列表',
    auth_father_id: '8nzhEmgmS',
    auth_father_name: '用户权限',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/user-auth/list',
    enable: false
  },
  {
    auth_description: '创建用户权限',
    auth_id: '8narmMp7Z',
    auth_name: '创建用户权限',
    auth_father_id: '8nzhEmgmS',
    auth_father_name: '用户权限',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/user-auth/create',
    enable: false
  },
  {
    auth_description: '更新用户权限',
    auth_id: 'diWnCwOeO',
    auth_name: '更新用户权限',
    auth_father_id: '8nzhEmgmS',
    auth_father_name: '用户权限',
    auth_sort: 2,
    auth_type: '2',
    auth_url: '/user-auth/update',
    enable: false
  },
  {
    auth_description: '删除用户权限',
    auth_id: 'xlhPC3Ca3',
    auth_name: '删除用户权限',
    auth_father_id: '8nzhEmgmS',
    auth_father_name: '用户权限',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/user-auth/delete',
    enable: false
  },
  {
    auth_description: '设置用户角色权限',
    auth_id: '13ZrguVlC',
    auth_name: '设置用户角色权限',
    auth_father_id: '8nzhEmgmS',
    auth_father_name: '用户权限',
    auth_sort: 4,
    auth_type: '2',
    auth_url: '/user-role-auth/set',
    enable: false
  },
  {
    auth_description: '设置管理员角色',
    auth_id: 'bjrc297SQ',
    auth_name: '设置管理员角色',
    auth_father_id: 'jKF3lIYO0',
    auth_father_name: '管理员管理',
    auth_sort: 4,
    auth_type: '2',
    auth_url: '/admin-user-role/create',
    enable: false
  },
  {
    auth_description: '管理员角色设置权限',
    auth_id: 'e7yBRAOsE',
    auth_name: '管理员角色设置权限',
    auth_father_id: 'f__A7Zf22',
    auth_father_name: '角色管理',
    auth_sort: 5,
    auth_type: '2',
    auth_url: '/admin-role-auth/set',
    enable: false
  },
  {
    auth_description: '用户头像审核',
    auth_id: 'F2cVbkCIn',
    auth_name: '用户头像审核',
    auth_father_id: 'f-_KRK5ZL',
    auth_father_name: '用户管理',
    auth_sort: 4,
    auth_type: '1',
    auth_url: 'user_avatar_review',
    enable: true
  },
  {
    auth_description: '获取待审核头像列表',
    auth_id: 'QOLvuDGrg',
    auth_name: '获取待审核头像列表',
    auth_father_id: 'F2cVbkCIn',
    auth_father_name: '用户头像审核',
    auth_sort: 0,
    auth_type: '2',
    auth_url: '/user/avatar-review-list',
    enable: false
  },
  {
    auth_description: '审核用户头像',
    auth_id: 'EJB_mpFOS',
    auth_name: '审核用户头像',
    auth_father_id: 'F2cVbkCIn',
    auth_father_name: '用户头像审核',
    auth_sort: 1,
    auth_type: '2',
    auth_url: '/user/avatar-review-set',
    enable: false
  },
  {
    auth_description: '禁言用户的评论或文章',
    auth_id: 'FH-mt55wt',
    auth_name: '禁言评论或文章',
    auth_father_id: 'lnRP0Lc5L',
    auth_father_name: '用户',
    auth_sort: 3,
    auth_type: '2',
    auth_url: '/user/ban',
    enable: false
  }
]
